<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <PropertyGroup Label="Docker container">
    <EnableSdkContainerSupport>true</EnableSdkContainerSupport>
    <ContainerFamily>cbl-mariner2.0</ContainerFamily>
    <RuntimeIdentifiers>linux-x64;linux-arm64</RuntimeIdentifiers>
    <ContainerImageTag>$(TargetFramework)</ContainerImageTag>
    <ContainerImageFormat>OCI</ContainerImageFormat>
    <ContainerArchiveOutputPath>$(RepoRoot)/artifacts/containers/</ContainerArchiveOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="..\..\tests\http\http-client.env.json" Link="http\http-client.env.json" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\tests\http\blocking-threads.http" Link="http\blocking-threads.http" />
    <None Include="..\..\tests\http\high-cpu.http" Link="http\high-cpu.http" />
    <None Include="..\..\tests\http\memory-leak.http" Link="http\memory-leak.http" />
    <None Include="..\..\tests\http\json.http" Link="http\json.http" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.2.3" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="http\" />
  </ItemGroup>

  <!-- BEGIN: These go away when the package ships for real -->
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Build.Containers" Version="8.0.407" GeneratePathProperty="true" />
  </ItemGroup>
  <PropertyGroup>
    <_ContainersTargetsDir>$(PkgMicrosoft_NET_Build_Containers)/build/</_ContainersTargetsDir>
  </PropertyGroup>
  <!-- END: These go away when the package ships for real -->

</Project>
